---
- name: Check AWS CLI version
  ansible.builtin.command: aws --version
  register: aws_version
  changed_when: false
  failed_when: false

- name: Exit role if AWS CLI is not installed
  ansible.builtin.meta: end_host
  when: aws_version.rc != 0

- name: Display AWS CLI version
  ansible.builtin.debug:
    msg: "{{ aws_version.stdout }}"

- name: Set file permissions for resticPassword
  become: true
  file:
    path: /data/resticPassword.txt
    mode: '0600'

- name: Git pull latest changes
  ansible.builtin.shell:
    cmd: git pull
    chdir: "/data/config_storage/compose"
