[[build]]
name = "skywatch"
[build.config]
builder = "holmie"
image_name = "skywatch"
include_latest_tag = false
include_version_tags = true
include_commit_tag = false
linked_repo = "compose_main"
build_path = "skywatch"
image_registry = [
  { domain = "git.holmlab.org", account = "shady" }
]

##

[[build]]
name = "storageview"
[build.config]
builder = "holmie"
image_name = "storageview"
linked_repo = "compose_main"
build_path = "storageview"
image_registry = [
  { domain = "git.holmlab.org", account = "shady" }
]

##

[[build]]
name = "tools_container"
[build.config]
builder = "holmie"
image_name = "tools_container"
linked_repo = "compose_main"
build_path = "tools_container"
dockerfile_path = "Dockerfile"
image_registry = [
  { domain = "git.holmlab.org", account = "shady" }
]