[[build]]
name = "skywatch"
[build.config]
builder = "holmie"
image_name = "skywatch"
linked_repo = "compose_main"
build_path = "skywatch"
image_registry = [
  { domain = "git.holmlab.org", account = "shady" }
]

##

[[build]]
name = "jenkins"
[build.config]
builder = "holmie"
auto_increment_version = false
image_name = "jenkins"
image_tag = "2.555.1-lts-jdk25"
include_latest_tag = false
include_version_tags = false
include_commit_tag = false
linked_repo = "compose_main"
build_path = "jenkins"
image_registry = [
  { domain = "git.holmlab.org", account = "shady" }
]

##

[[build]]
name = "storageview"
[build.config]
builder = "holmie"
image_name = "storageview"
linked_repo = "compose_main"
build_path = "storageview"
image_registry = [
  { domain = "git.holmlab.org", account = "shady" }
]

##

[[build]]
name = "tools_container"
[build.config]
builder = "holmie"
image_name = "tools_container"
linked_repo = "compose_main"
build_path = "tools_container"
dockerfile_path = "Dockerfile.tools_container"
image_registry = [
  { domain = "git.holmlab.org", account = "shady" }
]