---
services:
  tools_container:
    image: git.holmlab.org/shady/tools_container:0.2.1
  skywatch:
    image: git.holmlab.org/shady/skywatch:1.5.6
  storageview:
    image: git.holmlab.org/shady/storageview:0.0.3
  debian:
    image: debian:13.6@sha256:f324c7ff54321e8d9c588493a20244965938ce0aa50bbd1022d38010e9ffc4b1
