---
services:
  tools_container:
    image: git.holmlab.org/shady/tools_container:0.1.27
  skywatch:
    image: git.holmlab.org/shady/skywatch:1.5.2
  storageview:
    image: git.holmlab.org/shady/storageview:0.0.3
