---
services:
  tools_container:
    image: git.holmlab.org/shady/tools_container:0.1.25
  skywatch:
    image: git.holmlab.org/shady/skywatch:1.5.1
  storageview:
    image: git.holmlab.org/shady/storageview:0.0.3
