---
- hosts: all
  become: yes
  tasks:
    - name: Get hostname
      command: hostname
      register: hostname_output

    - name: Send ntfy notification
      uri:
        url: "https://ntfy.holmlab.org/updates1Q7Mjean"
        method: POST
        body: "hello from ansible"
        headers:
          Title: "updates ran on {{ hostname_output.stdout }}"
          Priority: "min"
