---
- hosts: all
  become: yes
  tasks:
    - name: Run apt update
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      register: update_output

    - name: Get hostname
      command: hostname
      register: hostname_output

    - name: Send ntfy notification
      uri:
        url: "https://ntfy.holmlab.org/updates1Q7Mjean"
        method: POST
        body: "{{ update_output.stdout }}"
        headers:
          Title: "updates ran on {{ hostname_output.stdout }}"
          Priority: "min"
      when: update_output.stdout is defined
