# the idea here is to auto-scan all the images inside compose.yaml and report via ntfy if any have bad CVE's
name: Scan images

on:
  push:
    branches: [main]
    paths:
      - '.forgejo/workflows/auto_scan.yaml'
  workflow_dispatch:

jobs:
  Grype-tools_container:
    runs-on: tools_container

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Run Grype on tools_container
        id: version
        env:
          CLICOLOR_FORCE: "1"
          TERM: xterm-256color
        run: |
          IMAGE=$(grep -m 1 'image:' compose.yaml | awk '{print $2}')
          echo "Running Grype on: $IMAGE"
          #grype $IMAGE --only-fixed --output json > grype-results.json

  Grype-skywatch:
    runs-on: tools_container

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Run Grype on skywatch
        id: version
        env:
          CLICOLOR_FORCE: "1"
          TERM: xterm-256color
        run: |
          IMAGE=$(grep -m 2 'image:' compose.yaml | tail -1 | awk '{print $2}')
          echo "Running Grype on: $IMAGE"
          #grype $IMAGE --only-fixed --output json > grype-results.json

  Grype-storageview:
    runs-on: tools_container

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Run Grype on storageview
        id: version
        env:
          CLICOLOR_FORCE: "1"
          TERM: xterm-256color
        run: |
          IMAGE=$(grep -m 3 'image:' compose.yaml | tail -1 | awk '{print $2}')
          echo "Running Grype on: $IMAGE"
          grype $IMAGE --only-fixed #--output json > grype-results.json
          cat grype-results.json
