# the idea here is to auto-scan all the images inside compose.yaml and report via ntfy if any have bad CVE's
name: Scan images

on:
  push:
    branches: [main]
    paths:
      - '.forgejo/workflows/auto_scan.yaml'
  workflow_dispatch:

jobs:
  Grype:
    runs-on: tools_container

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Run Grype on all images
        id: version
        env:
          CLICOLOR_FORCE: "1"
          TERM: xterm-256color
        run: |
          images=$(grep 'image:' compose.yaml | awk '{print $2}')
          for IMAGE in $images; do
            echo "🗨️ Running Grype on: $IMAGE"
            SHORT_IMAGE=${IMAGE#*/}
            SHORT_IMAGE=${SHORT_IMAGE##*/}
            SHORT_IMAGE=${SHORT_IMAGE%%:*}
            grype $IMAGE --only-fixed | grep -vF -e '< 0.1' -e 'N/A' > $SHORT_IMAGE.output.txt
            echo "---"
            cat $SHORT_IMAGE.output.txt
            sed 's/\x1b\[[0-9;]*m//g' $SHORT_IMAGE.output.txt | awk '{
                for(i=1;i<=NF;i++) if($i~/^(Critical|High|Medium|Low|Negligible|Unknown)$/) sev=$i
                print sev, $NF
            }' > tmp && mv tmp $SHORT_IMAGE.output.txt
            cat $SHORT_IMAGE.output.txt
            [[ $(wc -l < $SHORT_IMAGE.output.txt) -ne 1 ]] && sed -i '1d' $SHORT_IMAGE.output.txt && curl -X POST https://ntfy.holmlab.org/${{ secrets.NTFY_TOPIC }} \
              -H "Title: $SHORT_IMAGE CVE results" \
              -H "Priority: low" \
              --data-binary @$SHORT_IMAGE.output.txt
            echo "---"
          done
