name: Build tools_container

on:
  push:
  workflow_dispatch:

jobs:
  Build-tools_container:
    runs-on: tools_container

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine latest version
        id: version
        run: |
          https://git.holmlab.org/api/v1/packages/shady?type=container&limit=50

      - name: Clone compose
        run: |
          git clone https://git.holmlab.org/shady/compose.git

      - name: Is latest in runner-config.yml?
        register: needs_update

      - name: make pr to update it
        when: needs_update

      - name: Notify failure
        if: failure()
        run: |
          curl -X POST https://ntfy.holmlab.org/updates1Q7Mjean \
            -H "Title: ‼️ Actions failed" \
            -H "Priority: low" \
            -d "Workflow '${{ github.workflow }}' failed"
