name: Scan an image inside Holmie via ansible

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'image to scan'
        required: true
        type: string
        default: 'git.holmlab.org/shady/tools_container:0.1.14'

jobs:
  scan-tools_container:
    runs-on: tools_container

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Run Grype Ansible
        run: |
          echo "Running Grype on: ${{ github.event.inputs.image }}"
          ansible-playbook playbooks/grype.yaml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"  # alternative to known_hosts
          IMAGE: ${{ github.event.inputs.image }}

      - name: Notify failure
        if: failure()
        run: |
          curl -X POST https://ntfy.holmlab.org/${{ secrets.NTFY_TOPIC }} \
            -H "Title: ‼️ Actions failed" \
            -H "Priority: low" \
            -d "Workflow '${{ github.workflow }}' failed"
