name: Scan an image

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'image to scan'
        required: true
        type: string
        default: 'git.holmlab.org/shady/tools_container:0.1.14'

jobs:
  Grype:
    runs-on: tools_container

    steps:
      - name: Run Grype
        id: version
        env:
          CLICOLOR_FORCE: "1"
          TERM: xterm-256color
        run: |
          echo "Running Grype on: ${{ github.event.inputs.image }}"
          echo "+"
          grype "${{ github.event.inputs.image }}"
          echo "+"

      - name: Notify failure
        if: failure()
        run: |
          curl -X POST https://ntfy.holmlab.org/${{ secrets.NTFY_TOPIC }} \
            -H "Title: ‼️ Actions failed" \
            -H "Priority: low" \
            -d "Workflow '${{ github.workflow }}' failed"

  ClamAV:
    runs-on: tools_container

    steps:
      - name: Run ClamAV
        id: version
        env:
          CLICOLOR_FORCE: "1"
          TERM: xterm-256color
        run: |
          echo "Running ClamScan on: ${{ github.event.inputs.image }}"

          echo "+ export image for scanning"
          IMAGE="${{ github.event.inputs.image }}"
          TMPDIR=$(mktemp -d)

          echo "+ configure and start docker"
          mkdir -p /var/lib/docker
          dockerd --storage-driver=vfs &>/var/log/dockerd.log &
          until docker info &>/dev/null; do sleep 1; done
          sleep 10

          echo "+ docker create:"
          docker create --name tmp_scan "$IMAGE"
          echo "+ docker export:"
          docker export tmp_scan | tar -x -C "$TMPDIR"
          echo "+ docker rm:"
          docker rm tmp_scan

          echo "+ configure clamav"
          freshclam

          echo "+ scan image"
          clamscan -r "$TMPDIR"

          echo "+ clean up"
          rm -rf "$TMPDIR"

      - name: Notify failure
        if: failure()
        run: |
          curl -X POST https://ntfy.holmlab.org/${{ secrets.NTFY_TOPIC }} \
            -H "Title: ‼️ Actions failed" \
            -H "Priority: low" \
            -d "Workflow '${{ github.workflow }}' failed"
