name: Build and publish generic image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version to publish'
        required: true
        type: string
        default: '0.0.1'
      source_code:
        description: '.git link'
        required: true
        type: string
        default: 'https://github.com/monochrome-music/monochrome.git'
      name_to_publish:
        description: 'name to publish'
        required: true
        type: string
        default: 'monochrome'
      path:
        description: 'path - should match name cuz well cd there in a sec'
        required: true
        type: string
        default: 'monochrome'
      dockerfile:
        description: 'Dockerfile name'
        required: true
        type: string
        default: 'docker/Dockerfile'

jobs:
  Build-generic-image:
    runs-on: tools_container

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Clone code
        run: |
          git clone ${{ github.event.inputs.source_code }}

      - name: Build image
        run: |
          podman --version
          cd ${{ github.event.inputs.path }}
          podman --storage-driver vfs build --platform linux/amd64,linux/arm64 -f ${{ github.event.inputs.dockerfile }} -t ${{ github.event.inputs.name_to_publish }}:${{ github.event.inputs.version }} .

      - name: Push image version
        run: |
          buildah --storage-driver vfs push \
            --creds "${{ secrets.REGISTRY_USERNAME }}:${{ secrets.REGISTRY_PASSWORD }}" \
            ${{ github.event.inputs.name_to_publish }}:${{ github.event.inputs.version }} \
            docker://git.holmlab.org/shady/${{ github.event.inputs.name_to_publish }}:${{ github.event.inputs.version }}
