name: Use buildah to make tools_container

on:
  push:
    paths:
      - '.forgejo/workflows/modern_build.yaml'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish - Leave blank to auto-increment.'
        required: true
        type: string
        default: '0.1.4'

jobs:
  Build-skopeo:
    runs-on: tools_container

    steps:
      - name: print todo
        id: version
        run: |
          buildah --version
          echo "---"
          echo "Building version: ${{ github.event.inputs.version }}"
          echo "---"
