name: Send ntfy notification

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: debian

    steps:
      - name: Send ntfy notification
        run: |
          curl -d "hello from ansible" https://ntfy.holmlab.org/updates1Q7Mjean
