name: Run Webhook to restart Actions

on:
  push:
    paths:
      - 'runner-config.yml'
      - '.forgejo/workflows/restart_actions.yaml'
  workflow_dispatch:

jobs:
  restart-forgejo-actions:
    runs-on: tools_container

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run webhook
        run: |
          PAYLOAD='{"ref":"refs/heads/main"}'
          SIGNATURE=$(printf '%s' "$PAYLOAD" | openssl dgst -sha256 -hmac "$SECRET" | awk '{print $2}')
          curl -f -X POST https://komodo.holmlab.org/listener/github/repo/compose_test/pull \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature-256: sha256=${SIGNATURE}" \
            -d "$PAYLOAD"

      - name: Notify failure
        if: failure()
        run: |
          curl -X POST https://ntfy.holmlab.org/updates1Q7Mjean \
            -H "Title: ‼️ Actions failed" \
            -H "Priority: low" \
            -d "Workflow '${{ github.workflow }}' failed"
