name: Run Webhook to restart Actions

on:
  push:
    paths:
      - 'runner-config.yml'
      - '.forgejo/workflows/restart_actions.yaml'
    branches: [main]
  workflow_dispatch:

jobs:
  restart-forgejo-actions:
    runs-on: tools_container

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run webhook
        run: |
          curl -f -X POST https://komodo.holmlab.org/listener/gitlab/procedure/restart-forgejo-actions/main  \
            -H "Content-Type: application/json" \
            -H "X-Gitlab-Token:  ${{ secrets.WEBHOOK_PASSWORD }}" \
            -d '{"ref":"refs/heads/main"}'

      - name: Notify failure
        if: failure()
        run: |
          curl -X POST https://ntfy.holmlab.org/${{ secrets.NTFY_TOPIC }} \
            -H "Title: ‼️ Actions failed" \
            -H "Priority: low" \
            -d "Workflow '${{ github.workflow }}' failed"
