name: Deploy any Ansible Playbook

on:
  workflow_dispatch:
    inputs:
      playbook:
        description: "playbook:"
        required: true
        default: ""
        type: choice
        options:
          - mck
          - snow
          - turret
          - holmie
          - holmgarage
          - qbit_port
      extra_var:
        description: "extra_var:"
        required: false
        default: ""
        type: string

jobs:
  deploy:
    runs-on: tools_container

    steps:
      - name: Checkout
        uses: actions/checkout@v6..0.2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Run Ansible
        run: |
          echo "Running Ansible playbook ${{ github.event.inputs.playbook }} with var ${{ github.event.inputs.extra_var }}"
          ansible-playbook playbooks/${{ github.event.inputs.playbook }}.yaml \
            -e "extra_var='${{ github.event.inputs.extra_var }}'"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_BECOME_PASS: ${{ secrets.SUDO_PASSWORD }}
          ANSIBLE_FORCE_COLOR: "1"
          WEBHOOK_PASSWORD: ${{ secrets.WEBHOOK_PASSWORD }}

      - name: Notify failure
        if: failure()
        run: |
          curl -X POST https://ntfy.holmlab.org/${{ secrets.NTFY_TOPIC }} \
            -H "Title: ‼️ Actions failed" \
            -H "Priority: low" \
            -d "Workflow '${{ github.workflow }}' failed"
