name: Build tools_container on skopeo

on:
  push:
    paths:
      - '.forgejo/workflows/skopeo.yaml'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish - Leave blank to auto-increment.'
        required: true
        type: string
        default: '0.1.4'

jobs:
  Build-skopeo:
    runs-on: skopeo

    steps:
      - name: print todo
        id: version
        run: |
          echo "Version: ${{ github.event.inputs.version }}"
