name: Build tools_container

on:
  push:
    paths:
      - 'containers/Dockerfile.tools_container'
      - '.forgejo/workflows/skopeo.yaml'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish - Leave blank to auto-increment.'
        required: false
        type: string
        default: ''

jobs:
  Build-tools_container:
    runs-on: skopeo

    steps:
      - name: podman yeet
        run: |
          podman --version
          podman --help

      - name: Notify failure
        if: failure()
        run: |
          curl -X POST https://ntfy.holmlab.org/${{ secrets.NTFY_TOPIC }} \
            -H "Title: ‼️ Actions failed" \
            -H "Priority: low" \
            -d "Workflow '${{ github.workflow }}' failed"
