---
- name: Setup folders for samba
  block:
    - name: Set storage ownership recursively to uid/gid 1000
      become: true
      ansible.builtin.file:
        path: "/data/dont_backup/samba/storage"
        owner: 1000
        group: 1000
        recurse: true
        state: directory

    - name: Set config ownership recursively to uid/gid 1000
      become: true
      ansible.builtin.file:
        path: "/data/dont_backup/samba/config"
        owner: 1000
        group: 1000
        recurse: true
        state: directory

- name: Setup files for this service
  block:
    - name: Detect if file is actually a folder
      become: true
      ansible.builtin.stat:
        path: "/data/dont_backup/samba/config/smb.tmp"
      register: filemd_stat

    - name: Remove un-needed directory
      become: true
      ansible.builtin.command:
        cmd: rmdir /data/dont_backup/samba/config/smb.tmp
      when: filemd_stat.stat.exists and filemd_stat.stat.isdir

    - name: Set file ownership to uid/gid 1000
      become: true
      ansible.builtin.file:
        path: "/data/dont_backup/samba/config/smb.tmp"
        owner: 1000
        group: 1000
        state: touch
