---
- name: Setup folders for radicale
  block:
    - name: Set directory ownership recursively to uid/gid 1000
      become: true
      ansible.builtin.file:
        path: "/data/config_storage/radicale"
        owner: 1000
        group: 1000
        recurse: true
        state: directory

- name: Setup files for this service
  block:
    - name: CONFIG - Detect if file is actually a folder
      become: true
      ansible.builtin.stat:
        path: "/data/config_storage/radicale/config/config"
      register: config

    - name: CONFIG - Remove un-needed directory
      become: true
      ansible.builtin.command:
        cmd: rmdir /data/config_storage/radicale/config/config
      when: config.stat.exists and config.stat.isdir

    - name: CONFIG - Set file ownership to uid/gid 1000
      become: true
      ansible.builtin.file:
        path: "/data/config_storage/radicale/config/config"
        owner: 1000
        group: 1000
        state: touch

    - name: USERS - Detect if users file is actually a folder
      become: true
      ansible.builtin.stat:
        path: "/data/config_storage/radicale/config/users"
      register: users

    - name: USERS - Remove un-needed directory
      become: true
      ansible.builtin.command:
        cmd: rmdir /data/config_storage/radicale/config/users
      when: users.stat.exists and users.stat.isdir

    - name: USERS - Set users file ownership to uid/gid 1000
      become: true
      ansible.builtin.file:
        path: "/data/config_storage/radicale/config/users"
        owner: 1000
        group: 1000
        state: touch

- name: Template Radicale config file
  ansible.builtin.template:
    src: config.j2
    dest: "/data/config_storage/radicale/config/config"

- name: Get radicale user secret from Infisical
  ansible.builtin.command: >
    infisical secrets get shady
    --projectId="{{ lookup('env', 'INFISICAL_WORKSPACE') }}"
    --env=prod
    --path=/radicale
    --domain="{{ lookup('env', 'INFISICAL_URL') }}"
    --plain
  environment:
    INFISICAL_CLIENT_ID: "{{ lookup('env', 'INFISICAL_CLIENTID') }}"
    INFISICAL_CLIENT_SECRET: "{{ lookup('env', 'INFISICAL_CLIENTSECRET') }}"
  register: radicale_secret_raw
  no_log: false

- name: Set radicale credentials
  ansible.builtin.set_fact:
    radicale_user: "shady"
    radicale_password_hash: "{{ radicale_secret_raw.stdout | password_hash('bcrypt') }}"
  no_log: true

- name: Template radicale users file
  ansible.builtin.template:
    src: users.j2
    dest: /data/config_storage/radicale/config/users
    owner: 1000
    group: 1000
    mode: '0600'
  no_log: true
