FROM ghcr.io/moghtech/komodo-core:2.2.0

# Add Infisical repository
RUN curl -L 'https://artifacts-cli.infisical.com/setup.deb.sh' | bash

# Install infisical
RUN apt update
RUN apt install -y infisical
