FROM alpine:3.24.1

# Infisical setup
RUN apk add bash sudo wget
RUN wget -qO- 'https://artifacts-cli.infisical.com/setup.apk.sh' | sudo sh

RUN apk update
RUN apk add git python3 py3-pip nodejs npm openssh curl docker-cli docker jq openrc grype buildah podman clamav infisical qemu-aarch64

# from: https://www.jeffgeerling.com/blog/2023/how-solve-error-externally-managed-environment-when-installing-pip3/
RUN rm -rf /usr/lib/python3.14/EXTERNALLY-MANAGED
RUN pip3 install ansible

# install UDS
ARG UDS_VERSION=v0.36.0
RUN curl -fsS "https://github.com/defenseunicorns/uds-cli/releases/download/${UDS_VERSION}/uds-cli_${UDS_VERSION}_Linux_amd64" -o uds-linux-amd64
RUN chmod +x uds-linux-amd64
RUN mv uds-linux-amd64 /usr/local/bin/uds
