FROM ghcr.io/moghtech/komodo-core:2.2.0

# Install infisical
RUN curl -L 'https://artifacts-cli.infisical.com/setup.deb.sh' | bash \
    && apt update \
    && apt install -y infisical \
    && cp /usr/bin/infisical /usr/local/bin/infisical
