---
- name: Make and set permissions on /data/config_storage/navidrome
  ansible.builtin.file:
    path: /data/config_storage/navidrome
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'

- name: Make and set Music folder permissions
  ansible.builtin.file:
    path: /data/music
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'
