[Desktop Entry]
Categories=AudioVideo
Comment=Switch into a Plasma Bigscreen session
Exec=bash -c "sleep 30 && plasma-bigscreen-swap-session"
Icon=applications-multimedia
Name=Plasma Bigscreen
Terminal=false
Type=Application
