---
- name: Setup folders for trek
  block:
    - name: Set directory ownership recursively to uid/gid 0
      become: true
      ansible.builtin.file:
        path: "/data/config_storage/trek/data"
        owner: 0
        group: 0
        recurse: true
        state: directory
    - name: Set directory ownership recursively to uid/gid 0
      become: true
      ansible.builtin.file:
        path: "/data/config_storage/trek/uploads"
        owner: 0
        group: 0
        recurse: true
        state: directory
