---
- name: Setup folders for this zot
  block:
    - name: Set directory ownership recursively to uid/gid 1000
      become: true
      ansible.builtin.file:
        path: "/data/config_storage/zot"
        owner: 1000
        group: 1000
        recurse: true
        state: directory

- name: Setup files for this zot
  block:
    - name: Detect if file is actually a folder
      become: true
      ansible.builtin.stat:
        path: "/data/config_storage/zot/meta.db"
      register: filemd_stat

    - name: Remove un-needed directory
      become: true
      ansible.builtin.command:
        cmd: rmdir /data/config_storage/zot/meta.db
      when: filemd_stat.stat.exists and filemd_stat.stat.isdir

    - name: Set file ownership to uid/gid 1000
      become: true
      ansible.builtin.file:
        path: "/data/config_storage/zot/meta.db"
        owner: 1000
        group: 1000
        state: touch
