---
- name: Install packages
  become: true
  block:

    - name: Install plasma-bigscreen
      ansible.builtin.dnf:
        name: plasma-bigscreen
        state: present

    - name: Install Jellyfin desktop flatpack
      community.general.flatpak:
        name: org.jellyfin.JellyfinDesktop
        state: present
        remote: flathub

    - name: Install Plex htpc flatpack
      community.general.flatpak:
        name: tv.plex.PlexHTPC
        state: present
        remote: flathub

    - name: Install FCast flatpack
      community.general.flatpak:
        name: org.fcast.Receiver
        state: present
        remote: flathub

    - name: Install Feishin flatpack
      community.general.flatpak:
        name: org.jeffvli.feishin
        state: present
        remote: flathub

    - name: Install Spotify flatpack
      community.general.flatpak:
        name: com.spotify.Client
        state: present
        remote: flathub

    - name: Enable blakegardner/xremap COPR
      ansible.builtin.command: dnf copr enable -y blakegardner/xremap
      args:
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:blakegardner:xremap.repo

    - name: Install xremap
      ansible.builtin.dnf:
        name: xremap
        state: present

- name: Configure xremap
  become: true
  block:

    - name: create directory
      ansible.builtin.file:
        path: "/etc/xremap"
        recurse: true
        state: directory
      register: xremap_dir

    - name: Template config.yaml
      ansible.builtin.template:
        src: config.yaml
        dest: /etc/xremap/config.yaml
      register: xremap_config

    - name: Template systemd service xremap.service
      ansible.builtin.template:
        src: xremap.service
        dest: /etc/systemd/system/xremap.service
      register: xremap_service

    - name: Reload systemd units if needed
      ansible.builtin.command: systemctl daemon-reload
      when:  xremap_dir.changed or xremap_config.changed or xremap_service.changed

    - name: Enable and start xremap
      ansible.builtin.service:
        name: xremap
        enabled: true
        state: started

- name: autostart bigscreen
  ansible.builtin.template:
    src: autostart.conf
    dest: /home/tv/.config/autostart/plasma-bigscreen-swap-session.desktop

- name: Others
  block:

    - name: Disable KDE Wallet subsystem
      ansible.builtin.ini_file:
        path: ansible_facts["HOME"]"/.config/kwalletrc"
        section: Wallet
        option: Enabled
        value: "false"

    - name: Disable KDE Wallet first run prompt
      ansible.builtin.ini_file:
        path: ansible_facts["HOME"]"/.config/kwalletrc"
        section: Wallet
        option: First Use
        value: "false"

    - name: Configure kwinrc - hidecursor plugin enabled
      ansible.builtin.ini_file:
        path: /home/tv/.config/kwinrc
        section: Plugins
        option: hidecursorEnabled
        value: "true"
      register: kwinrc_plugins

    - name: Configure kwinrc - hidecursor idle time
      ansible.builtin.ini_file:
        path: /home/tv/.config/kwinrc
        section: Plugin-hidecursor
        option: idleTime
        value: "3000"
      register: kwinrc_plugin_hidecursor
