---
- name: Install packages
  become: true
  block:

    - name: Install plasma-bigscreen
      ansible.builtin.dnf:
        name: plasma-bigscreen
        state: present

    - name: Install Jellyfin desktop flatpack
      community.general.flatpak:
        name: org.jellyfin.JellyfinDesktop
        state: present
        remote: flathub

    - name: Enable blakegardner/xremap COPR
      ansible.builtin.command: dnf copr enable -y blakegardner/xremap
      args:
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:blakegardner:xremap.repo

    - name: Install xremap
      ansible.builtin.dnf:
        name: xremap
        state: present

- name: Configure xremap
  become: true
  block:

    - name: create directory
      ansible.builtin.file:
        path: "/etc/xremap"
        recurse: true
        state: directory
      register: xremap_dir

    - name: Template config.yml
      ansible.builtin.template:
        src: config.yml
        dest: /etc/xremap/config.yml
      register: xremap_config

    - name: Template systemd service xremap.service
      ansible.builtin.template:
        src: xremap.service
        dest: /etc/systemd/system/xremap.service
      register: xremap_service

    - name: Reload systemd units if needed
      ansible.builtin.command: systemctl daemon-reload
      when:  xremap_dir.changed or xremap_config.changed or xremap_service.changed

    - name: Enable and start xremap
      ansible.builtin.service:
        name: xremap
        enabled: true
        state: started

- name: Set plasma-bigscreen as default session
  become: true
  block:

    - name: SDDM is installed
      ansible.builtin.dnf:
        name: sddm
        state: present

    - name: Ensure SDDM drop-in config directory exists
      ansible.builtin.file:
        path: /etc/sddm.conf.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Check current systemd default target
      ansible.builtin.command: systemctl get-default
      register: current_default_target
      changed_when: false

    - name: Set systemd default target to graphical
      ansible.builtin.command: systemctl set-default graphical.target
      when: current_default_target.stdout != "graphical.target"
      changed_when: true

    - name: Ensure plasmalogin service is enabled
      ansible.builtin.systemd:
        name: plasmalogin
        enabled: true
