---
- name: Install plasma-bigscreen
  become: true
  ansible.builtin.dnf:
    name: plasma-bigscreen
    state: present

- name: Install Jellyfin desktop flatpack
  become: true
  community.general.flatpak:
    name: org.jellyfin.JellyfinDesktop
    state: present
    remote: flathub

- name: Enable COPR repo and install xremap
  become: true
  block:
    - name: Enable blakegardner/xremap COPR
      ansible.builtin.command: dnf copr enable -y blakegardner/xremap
      args:
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:blakegardner:xremap.repo

    - name: Install xremap
      ansible.builtin.dnf:
        name: xremap
        state: present

- name: Template files
  become: true
  block:

    - name: create directory
      become: true
      ansible.builtin.file:
        path: "/etc/xremap"
        recurse: true
        state: directory

    - name: Template config.yml
      ansible.builtin.template:
        src: config.yml
        dest: /etc/xremap/config.yml

    - name: Template systemd service xremap.service
      ansible.builtin.template:
        src: xremap.service
        dest: /etc/systemd/system/xremap.service


- name: Reload systemd units
  become: true
  ansible.builtin.command: systemctl daemon-reload

- name: Enable and start xremap
  become: true
  ansible.builtin.service:
    name: xremap
    enabled: true
    state: started
