---
- name: Is nut installed?
  become: true

  block:
    - name: Check for nut package installation
      ansible.builtin.package:
        name: nut
        state: present
      check_mode: yes
      register: nut_check
      changed_when: false

    - name: Fail if nut is not installed
      ansible.builtin.fail:
        msg: "Package 'nut' is not installed."
      when: nut_check is failed or (nut_check is defined and (nut_check.msg is defined or nut_check.rc is defined and nut_check.rc != 0))

- name: Template files
  become: true

  block:
    - name: Template ups.conf
      ansible.builtin.template:
        src: ups.conf
        dest: /etc/nut/ups.conf
      register: ups_conf

    - name: Template upsd.conf
      ansible.builtin.template:
        src: upsd.conf
        dest: /etc/nut/upsd.conf
      register: upsd_conf

    - name: Template upsd.users
      ansible.builtin.template:
        src: upsd.users
        dest: /etc/nut/upsd.users
      register: upsd_users

    - name: Template upsmon.conf
      ansible.builtin.template:
        src: upsmon.conf
        dest: /etc/nut/upsmon.conf
      register: upsman_conf

    - name: Template nut.conf
      ansible.builtin.template:
        src: nut.conf
        dest: /etc/nut/nut.conf
      register: nut_conf

- name: Restart nut if changes
  become: true
  ansible.builtin.shell:
    cmd: systemctl restart nut-server && systemctl enable nut-server && systemctl restart nut-monitor && systemctl enable nut-monitor
  when: ups_conf.changed or upsd_conf.changed or upsd_users.changed or upsman_conf.changed or nut_conf.changed

- name: Configure nut ntfy

  block:
    - name: Clone IaC repo
      ansible.builtin.git:
        repo: "https://git.holmlab.org/shady/IaC"
        dest: "/data/config_storage/IaC"
        version: "main"
        force: yes
        update: yes
    - name: Setup cron for 75% script
      become: true
      ansible.builtin.cron:
        name: "Every 5 minutes, every hour, every day - NUT"
        minute: "*/5"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/data/config_storage/IaC/roles/nut_setup/files/nut.sh"
        user: "root"
        state: present