---
- name: Is nut installed?
  become: true

  block:
    - name: Check for nut package installation
      apt:
        name: nut
        state: present
      check_mode: yes
      register: nut_check
      changed_when: false

    - name: Fail if nut is not installed
      fail:
        msg: "Package 'nut' is not installed."
      when: nut_check is failed or (nut_check is defined and (nut_check.msg is defined or nut_check.rc is defined and nut_check.rc != 0))
