---
- name: Run Grype
  hosts: holmie@192.168.50.65
  become: false

  tasks:
    - name: Run grype scan on {{ lookup('ansible.builtin.env', 'IMAGE') }}
      ansible.builtin.shell:
        cmd: /home/linuxbrew/.linuxbrew/bin/grype {{ lookup('ansible.builtin.env', 'IMAGE') }} --output template --template /home/linuxbrew/.linuxbrew/share/grype/templates/table.tmpl > /tmp/grype-report.txt
      changed_when: false

    - name: Display grype report
      ansible.builtin.shell:
        cmd: cat /tmp/grype-report.txt
      changed_when: false
      register: report

    - name: Show report
      ansible.builtin.debug:
        msg: "{{ report.stdout_lines }}"
