- name: holmie
  hosts: holmie@192.168.50.65
  roles:
    - roles/backups
    - roles/navidrome
    - roles/forgejo_actions
    - roles/chronoframe
    - roles/zot
    - roles/grimmory
    - roles/netalertx
    - roles/docmost
