---
- name: Configure infisical CLI inside Komodo
  hosts: controller
  become: true

  tasks:
    - name: install infisical
      ansible.builtin.shell: |
        docker exec -it komodo-core \
        curl -1sLf 'https://artifacts-cli.infisical.com/setup.deb.sh' | bash && \
        apt-get update

    - name: configure infisical
      ansible.builtin.shell: |
        docker exec -it komodo-core \
        apt-get install -y infisical jq && \
        export INFISICAL_TOKEN=$(curl -s -X POST https://infisical.holmlab.org/api/v1/auth/universal-auth/login \
          -H "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "clientId={{ lookup('ansible.builtin.env', 'INFISICAL_CLIENTID') }}" \
          --data-urlencode "clientSecret={{ lookup('ansible.builtin.env', 'INFISICAL_CLIENTSECRET') }}" \
          | jq -r '.accessToken')
